kind = "web"
previewPath = "/"
title = "RazaMonitor"
version = "1.0.0"
id = "artifacts/razamonitor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 18630
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/razamonitor run dev"

[services.env]
PORT = "18630"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/razamonitor", "run", "build"]
publicDir = "artifacts/razamonitor/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
